config/routes.rb
Rails.application.routes.draw do
  resources :events

  resources :subscribes

  resources :users, only: [ :new, :create, :update, :edit, :show, :index ] do
	  member do
	    get :activate
	  end
  end
  resources :sessions
  
  root 'events#index'
  get 'login', to: 'sessions#new', as: :login
  get 'signup', to: 'users#new', as: :signup
  get 'logout', to: 'sessions#destroy', as: :logout

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :subscribes
end

app/models/subscribe.rb
class Subscribe < ActiveRecord::Base
  	validates :user_id, presence: true
  	validates :event_id, presence: true
	belongs_to :user
	belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  has_many :events, dependent: :delete_all
  has_many :subscribes, dependent: :destroy

  VALID_EMAIL_REGEX =/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  VALID_NAME_REGEX = /\A[A-Za-z][A-Za-z0-9._-]{2,19}\z/
  validates :name, presence: true, 
                            length: { maximum: 50 }, 
                            format: { with: VALID_NAME_REGEX },
                            uniqueness: { case_sensitive: false }
  validates :email, presence: true,
                            format: { with: VALID_EMAIL_REGEX },
                            uniqueness: { case_sensitive: true }
  validates :password, presence: true, 
                                  confirmation: true,
                                  length: { in: 6..16 },
                                  on: :create

  def subscribed?(event)
    subscribes.find_by(event_id: event.id)
  end

  def subscribe!(user_id, event_id)
    subscribes.create!(user_id: user_id, event_id: event_id)
  end  

  def unsubscribe!(event_id)
    subscribes.find_by(event_id: event_id).destroy
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
          @event = Event.find(params[:id])
         if current_user.nil?
            redirect_to login_url, alert: "Not authorized! Please log in."
         else
            
         end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:user_id,:title,:venue,:pic,:starts_at)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
before_action :not_login_user, only: [ :new ]

  def new
    @user = User.new
  end

  def create
     if @user = login(params[:session][:email], params[:session][:password], params[:session][:remember])
      flash[:success] = "#{t('.successfully')}"
      respond_to do |format|
          format.html { redirect_to root_path }
          format.js
      end
    else
      user = User.find_by_email(params[:session][:email])
      if user && user.activation_state == "pending"
        flash.now[:warning] = "sessions.new.inactivation"
        @inactivation = true
      else
        flash.now[:error] = "#{t('sessions.new.invalid_email_password_combination')}"
      end
        respond_to do |format|
          format.html { render action: 'new' }
          format.js
        end
    end
  end

  def destroy
    logout
    redirect_to root_path
    flash[:success] = "#{t('.successfully')}"
  end

  private

    def not_login_user
    if logged_in?
      redirect_to root_path
      flash[:warning] = "#{t('users.has_already_logged_in')}"
    end
  end
end

app/controllers/subscribes_controller.rb
class SubscribesController < ApplicationController
	def new
		@subscribes = Subscribe.new
	end

	def create
		user_id = current_user.id
		event_id = params[:event_id]
		@subscribes = Subscribe.new(user_id: user_id, event_id: event_id)
		@subscribes.save
		redirect_to events_path
	end

	def subscribe_params
		raise params.inspect
    	params.require(:subscribe).permit(:event_id)   
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :not_login_user, only: [:show, :new, :create ]
  
	def index
    @users = User.all
  end


  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    @signup = true
  end

  def create
    @user = User.new(user_params)
    Rails.logger.info @user.valid?
    Rails.logger.info @user.errors
    if @user.save
      @user.activate!
      flash[:success] = "#{t('.successfully')}"
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'new' }
        format.js
      end
    end
  end
  def activate
    if (@user = User.load_from_activation_token(params[:id]))
      @user.activate!
      flash[:success] = "#{t('.activated')}"
      auto_login(@user)
    else
      not_authenticated
    end
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password,:password_confirmation)
  end
  
  def not_login_user
    if logged_in? and !current_user
      redirect_to root_path
      flash[:warning] = "#{t('users.has_already_logged_in')}"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div  class="form">
    
<%= form_for(@event) do |f| %>
    
      <div class="field-wrap">
        <%= f.label :title %><br>
        <%= f.text_field :title, placeholder: "Title of event"%>
      </div>
      <div class="field-wrap">
        <%= f.label :venue %><br>
        <%= f.text_field :venue %>
      </div>
      <div class="field-wrap">
        <%= f.label :starts_at, value: "start time" %><br>
        <%= f.datetime_select :starts_at %>
      </div>
      <div class="field-wrap">
        <%= f.label :pic %><br>
        <%= f.text_field :pic %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
<% end %>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<% if current_user %> <%= link_to( image_tag( "plus.png" , {size: '30x30'}), new_event_path) %><% end %>

<div class="row">
  <% @events.each do |event| %>  
  <div class="col-sm-8 col-xs-6 eventc">        
    <div class="panel panel-default">          
      <div class="panel-thumbnail">
        <img src="<%= event.pic %>" class="img-fixed">
      </div>          
      <div class="panel-body">            
        <p class="title"><%= link_to event.title, event %></p>            
        <p><%= event.venue %></p>
        <p><%= event.starts_at %></p>                    
        <p>
            <img src="http://api.randomuser.me/portraits/med/men/20.jpg" height="28px" width="28px">              
            <img src="http://api.randomuser.me/portraits/med/men/21.jpg" height="28px" width="28px">              
            <img src="http://api.randomuser.me/portraits/med/men/14.jpg" height="28px" width="28px">            
        </p>  
        <% if current_user && event.user == current_user %><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %><% end %>
        <% if event.user == current_user %><%= link_to 'Edit', edit_event_path(event) %><% end %>    
        <% if current_user && !current_user.subscribed?(event)%><%= link_to 'Subscribe', subscribes_path(event_id: event.id), method: :post %>
        <% end %>
      </div>
    </div>      
  </div><!--/col-->            
  <% end %>                    
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @event.venue %>
</p>

<p>
  <strong>Start Time:</strong>
  <%= @event.starts_at %>
</p>

<p>
  <strong>Pic:</strong>
  <%= @event.pic %>
</p>
<p>
<% @event.subscribes.each do |subscribe| %>
<p>
<%= subscribe.user.name%>
</p>
<% end %> 
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Evento</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
       <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Evento</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li <% if current_page?(events_path) -%>class="active"<% end -%>>
              <%= link_to 'Home', events_path %>
            </li>
            <li <% if current_page?(users_path) -%>class="active"<% end -%>>
              <%= link_to 'Users', users_path %>
            </li>        
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li>Logged in as <%= current_user.name %>.</li>
              <li><%= link_to "Log Out", logout_path %></li>
            <% else %>
              <li><%= link_to "Sign Up", signup_path %></li>
              <li><%= link_to "Log In", login_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

		<% flash.each do |key, value| %>
		<%= content_tag(:div, class: "alert alert-#{key}") do %>
		<p><%= value %></p>
		<% end %>
	<% end %>
	<div class="container">
    <div class="center">
			<%= yield %>
    </div>
	</div>

  <div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
	<div class="ui error message">
		<i class="close icon"></i>
		<div class="header">
			<%= t('.the_form_contains') %> 
			<% if I18n.locale.to_s == "de" %>
			<%= object.errors.count %>
				errors
			<% else %>
			<%= pluralize(object.errors.count, "error") %>
			<% end %>
		</div>
		<ul class="list">
			<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
</div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key , value| %>
	<div id="t-flash" class="ui <%= key %> message flash center aligned segment">
  	  <%= value %>
  </div>
<% end %>
<script>
  $(function(){
    setTimeout(function(){
      $(".ui.flash").closest(".message").addClass('animated fadeOutUp')
                                                        .one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', 
      function(){
        $('#t-flash').remove();
      });
    },3000)
  })
</script>

app/views/users/create.js.erb
$('.ui.form').removeClass('loading')
<% if @user.errors.empty? %>
  Turbolinks.visit('<%= root_path %>');
<% else %>
  $('#signup-errors').html("<%= j render 'shared/error_messages', object: @user %>");
  $('#error_explanation').transition('tada');
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<p id="notice"><%= notice %></p>

<div class="row">
<% @users.each do |user| %>  
  <div class="col-sm-8 col-xs-6 eventc">        
    <div class="panel panel-default">  
      <div class="panel-thumbnail">
        <img src="assets/user" class="img-fixed">
      </div>                       
      <div class="panel-body">            
        <p class="title"><%= link_to user.name, user %></p>
        <p><%= user.email %></p>                                             
      </div>
    </div>      
  </div><!--/col-->            
  <% end %>                    
</div>

app/views/users/new.html.erb
<div class="signup-form">
	<div id="signup-errors">
		
	</div>
	<%= form_for @user, remote: true do |f| %>
	<div class="ui one column center aligned grid">
  		<div class="column six wide form-holder">
    		
    		<div class="ui form">
    		<h2 class="formtitle">Create account</h2>
      			<div class="field">
					<div class="ui left icon large input">
						<%= f.text_field :name, placeholder: "#{t('activerecord.attributes.user.name')} (required)" %>
						<i class="user icon"></i>
					</div>
				</div>
				<div class="field">
					<div class="ui left icon large input">
						<%= f.text_field :email, placeholder: "#{t('activerecord.attributes.user.email')}(required)" %>
						<i class="mail icon"></i>
					</div>
				</div>
				<div class="field">
					<div class="ui left icon large input">
						<%= f.password_field :password, placeholder: "#{t('activerecord.attributes.user.password')}(required)" %>
						<i class="lock icon"></i>
					</div>
				</div>
				<div class="field">
					<div class="ui left icon large input">
						<%= f.password_field :password_confirmation, placeholder: "#{t('activerecord.attributes.user.password_confirmation')}(required)" %>
						<i class="lock icon"></i>
					</div>
				</div>
				<%= f.submit "#{t('users.signup')}", class: "ui fluid green large button", data: { disable_with: "#{t('form.submitting')}" } %>
			</div>
		</div>
	</div>
	<% end %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>